#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
