#!/usr/bin/env bash
# Include a custom 404 page that contains a string

ADD404_NOTFOUND="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
PATTERN="#error_page 404 /404.html;"


echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "47i\ $PATTERN$ADD404_NOTFOUND" /etc/nginx/sites-available/default
sudo service nginx restart
